'use client';

import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';

interface UcapanItem {
    id: string;
    name: string;
    attendance?: string;
    message: string;
    relationship?: string;
    createdAt: string;
}

// 2 KARTU BESAR PER LEMBAR AGAR RUANG SANGAT LEGA & BESAR
const WISHES_PER_SHEET = 2;

// Taburan Bintang Intan Kejora
const TWINKLING_STARS = [
    { id: 1, top: '4%', left: '8%', size: 14, delay: '0s', duration: '2.8s' },
    { id: 2, top: '9%', right: '12%', size: 18, delay: '1.2s', duration: '3.4s' },
    { id: 3, top: '18%', left: '82%', size: 12, delay: '0.6s', duration: '2.5s' },
    { id: 4, top: '27%', left: '6%', size: 16, delay: '1.8s', duration: '3.8s' },
    { id: 5, top: '38%', right: '8%', size: 20, delay: '0.3s', duration: '4s' },
    { id: 6, top: '52%', left: '10%', size: 14, delay: '2.1s', duration: '3.1s' },
    { id: 7, top: '65%', right: '14%', size: 16, delay: '1.5s', duration: '2.9s' },
    { id: 8, top: '78%', left: '7%', size: 18, delay: '0.9s', duration: '3.6s' },
    { id: 9, top: '88%', right: '9%', size: 13, delay: '2.4s', duration: '2.7s' },
    { id: 10, top: '95%', left: '42%', size: 15, delay: '1.1s', duration: '3.3s' },
];

// Debu Emas Melayang ke Atas
const GOLDEN_STARDUST = [
    { id: 1, left: '6%', delay: '0s', duration: '9s', size: 3, opacity: 0.8 },
    { id: 2, left: '18%', delay: '2.5s', duration: '12s', size: 4, opacity: 0.9 },
    { id: 3, left: '32%', delay: '1s', duration: '8.5s', size: 2.5, opacity: 0.7 },
    { id: 4, left: '48%', delay: '4s', duration: '11s', size: 3.5, opacity: 0.85 },
    { id: 5, left: '64%', delay: '1.8s', duration: '10s', size: 2, opacity: 0.6 },
    { id: 6, left: '78%', delay: '3.2s', duration: '13s', size: 4, opacity: 0.9 },
    { id: 7, left: '91%', delay: '0.8s', duration: '9.5s', size: 3, opacity: 0.75 },
    { id: 8, left: '12%', delay: '5s', duration: '10.5s', size: 2.5, opacity: 0.8 },
    { id: 9, left: '40%', delay: '6.2s', duration: '11.5s', size: 3, opacity: 0.7 },
    { id: 10, left: '85%', delay: '4.7s', duration: '8.8s', size: 4.5, opacity: 0.95 },
];

function getAutoGeneratedPhoto(name: string) {
    const seed = encodeURIComponent(name.trim().toLowerCase());
    return `https://i.pravatar.cc/150?u=${seed}`;
}

// Ornamen Sudut Filigree Klasik Ukiran Emas
function MiniCornerFiligree({ className = '' }: { className?: string }) {
    return (
        <svg viewBox="0 0 45 45" fill="none" className={`w-8 h-8 pointer-events-none ${className}`}>
            <path
                d="M 3 3 L 26 3 C 26 3 20 12 12 12 C 12 20 3 26 3 26 Z"
                stroke="#F59E0B"
                strokeWidth="1.2"
                fill="rgba(245,158,11,0.12)"
            />
            <circle cx="8" cy="8" r="2.5" fill="#FDE68A" />
            <path d="M 5 5 Q 16 5 16 16" stroke="#FDE68A" strokeWidth="0.8" strokeDasharray="1.5 1.5" />
        </svg>
    );
}

// Cincin Mahkota Emas Berputar Mengitari Foto Tamu
function RotatingAvatarWreath() {
    return (
        <div className="absolute -inset-1.5 pointer-events-none animate-[spin_20s_linear_infinite]">
            <svg viewBox="0 0 100 100" fill="none" className="w-full h-full">
                <circle cx="50" cy="50" r="46" stroke="#F59E0B" strokeWidth="1.2" strokeDasharray="4 3" opacity="0.8" />
                <circle cx="50" cy="50" r="49" stroke="#FDE68A" strokeWidth="0.6" strokeDasharray="1 5" opacity="0.6" />
                {[0, 90, 180, 270].map((deg) => (
                    <g key={deg} transform={`rotate(${deg} 50 50)`}>
                        <circle cx="50" cy="4" r="2" fill="#FDE68A" />
                    </g>
                ))}
            </svg>
        </div>
    );
}

// Bintang Intan 4-Point SVG
function DiamondStar({ size = 16, className = '' }: { size?: number; className?: string }) {
    return (
        <svg
            width={size}
            height={size}
            viewBox="0 0 24 24"
            fill="none"
            className={`pointer-events-none ${className}`}
        >
            <path
                d="M12 0 L14.2 9.8 L24 12 L14.2 14.2 L12 24 L9.8 14.2 L0 12 L9.8 9.8 Z"
                fill="url(#goldStarGradEngineBig)"
            />
            <circle cx="12" cy="12" r="2" fill="#FFFFFF" />
            <defs>
                <radialGradient id="goldStarGradEngineBig" cx="50%" cy="50%" r="50%">
                    <stop stopColor="#FFF" offset="0%" />
                    <stop stopColor="#FDE68A" offset="40%" />
                    <stop stopColor="#F59E0B" offset="80%" />
                    <stop stopColor="#B45309" offset="100%" />
                </radialGradient>
            </defs>
        </svg>
    );
}

// Mandala Raksasa Celestial Astrolabe Berputar di Latar
function CelestialMandalaBackground() {
    return (
        <div className="absolute top-[28%] left-1/2 -translate-x-1/2 -translate-y-1/2 w-[520px] h-[520px] pointer-events-none opacity-[0.09] animate-[spin_120s_linear_infinite]">
            <svg viewBox="0 0 400 400" fill="none" className="w-full h-full">
                <circle cx="200" cy="200" r="195" stroke="#FDE68A" strokeWidth="1" strokeDasharray="3 4" />
                <circle cx="200" cy="200" r="175" stroke="#F59E0B" strokeWidth="1.5" />
                <circle cx="200" cy="200" r="150" stroke="#FDE68A" strokeWidth="0.8" strokeDasharray="8 6" />
                <circle cx="200" cy="200" r="120" stroke="#F59E0B" strokeWidth="1.8" />
                <circle cx="200" cy="200" r="80" stroke="#FDE68A" strokeWidth="1" strokeDasharray="4 4" />
                <circle cx="200" cy="200" r="40" stroke="#F59E0B" strokeWidth="1.2" />
                {[0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330].map((deg) => (
                    <line
                        key={deg}
                        x1="200"
                        y1="5"
                        x2="200"
                        y2="395"
                        stroke="#FDE68A"
                        strokeWidth="0.8"
                        transform={`rotate(${deg} 200 200)`}
                    />
                ))}
                {[0, 45, 90, 135, 180, 225, 270, 315].map((deg) => (
                    <g key={deg} transform={`rotate(${deg} 200 200)`}>
                        <polygon points="200,25 208,60 200,50 192,60" fill="#F59E0B" />
                    </g>
                ))}
            </svg>
        </div>
    );
}

export default function UcapanPage() {
    const [wishes, setWishes] = useState<UcapanItem[]>([]);
    const [searchQuery, setSearchQuery] = useState('');
    const [isLoaded, setIsLoaded] = useState(false);

    // State Halaman Buku Fisik
    const [currentPage, setCurrentPage] = useState(0);
    const [bookKey, setBookKey] = useState(0);
    const bookElRef = useRef<HTMLDivElement>(null);
    const pageFlipInstanceRef = useRef<any>(null);

    useEffect(() => {
        async function loadRealWishes() {
            try {
                // Diarahkan langsung ke jembatan PHP statis
                const res = await fetch('/api_wishes.php', { cache: 'no-store' });
                if (res.ok) {
                    const apiData = await res.json();
                    if (Array.isArray(apiData)) {
                        setWishes(apiData);
                        try {
                            localStorage.setItem('wedding_wishes', JSON.stringify(apiData));
                        } catch { }
                    }
                }
            } catch {
                try {
                    const saved = localStorage.getItem('wedding_wishes');
                    if (saved) setWishes(JSON.parse(saved));
                } catch { }
            } finally {
                setIsLoaded(true);
            }
        }

        loadRealWishes();
    }, []);

    const totalHadir = wishes.filter(
        (w) => w.attendance && w.attendance.includes('Hadir') && !w.attendance.includes('Berhalangan')
    ).length;

    const filteredWishes = wishes.filter(
        (item) =>
            item.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            item.message.toLowerCase().includes(searchQuery.toLowerCase())
    );

    // Bagi data ke lembaran (2 ucapan per lembar agar kartu tampil besar)
    const sheets: UcapanItem[][] = [];
    for (let i = 0; i < filteredWishes.length; i += WISHES_PER_SHEET) {
        sheets.push(filteredWishes.slice(i, i + WISHES_PER_SHEET));
    }
    const totalSheets = Math.max(1, sheets.length);

    useEffect(() => {
        setCurrentPage(0);
        setBookKey((k) => k + 1);
    }, [filteredWishes.length, searchQuery]);

    // INISIALISASI ENGINE FISIKA KERTAS ST-PAGE-FLIP
    useEffect(() => {
        if (!isLoaded || sheets.length === 0) return;

        let isMounted = true;

        const timer = setTimeout(async () => {
            try {
                // @ts-ignore: Dynamic import untuk SSR Next.js
                const { PageFlip } = await import('page-flip');
                if (!bookElRef.current || !isMounted) return;

                if (pageFlipInstanceRef.current) {
                    try {
                        pageFlipInstanceRef.current.destroy();
                    } catch { }
                    pageFlipInstanceRef.current = null;
                }

                const bookEl = bookElRef.current;
                const pageElements = bookEl.querySelectorAll<HTMLElement>('.page-sheet-item');
                if (pageElements.length === 0) return;

                const pageFlip = new PageFlip(bookEl, {
                    width: 390,
                    height: 580,
                    size: 'stretch',
                    minWidth: 300,
                    maxWidth: 440,
                    minHeight: 520,
                    maxHeight: 640,
                    drawShadow: true,
                    maxShadowOpacity: 0.85,
                    showCover: false,
                    usePortrait: true,
                    autoSize: true,
                    flippingTime: 700,
                    useMouseEvents: true,
                    swipeDistance: 25,
                    clickEventForward: true,
                });

                pageFlip.loadFromHTML(pageElements);

                pageFlip.on('flip', (e: any) => {
                    if (isMounted) setCurrentPage(e.data);
                });

                pageFlipInstanceRef.current = pageFlip;
            } catch (err) {
                console.error('PageFlip init error:', err);
            }
        }, 120);

        return () => {
            isMounted = false;
            clearTimeout(timer);
            if (pageFlipInstanceRef.current) {
                try {
                    pageFlipInstanceRef.current.destroy();
                } catch { }
                pageFlipInstanceRef.current = null;
            }
        };
    }, [bookKey, isLoaded, sheets.length]);

    const handleTurnNext = () => {
        if (pageFlipInstanceRef.current) {
            pageFlipInstanceRef.current.flipNext('bottom');
        }
    };

    const handleTurnPrev = () => {
        if (pageFlipInstanceRef.current) {
            pageFlipInstanceRef.current.flipPrev('top');
        }
    };

    return (
        <div className="w-full min-h-screen flex justify-center bg-[#02050B] select-none relative font-sans antialiased">
            <main className="w-full max-w-md bg-gradient-to-b from-[#081124] via-[#050C1B] to-[#02050D] relative border-x-2 border-[#D97706]/40 shadow-[0_0_100px_rgba(217,119,6,0.3)] min-h-screen text-[#F1F5F9] pb-24 overflow-hidden">

                {/* CSS KEYFRAMES */}
                <style>{`
          @keyframes stardustFloat {
            0% { transform: translateY(110vh) scale(0.6); opacity: 0; }
            30% { opacity: 0.9; }
            70% { opacity: 0.8; }
            100% { transform: translateY(-10vh) scale(1.2); opacity: 0; }
          }
          @keyframes pulseCrown {
            0%, 100% { transform: scale(1); filter: drop-shadow(0 0 8px rgba(245,158,11,0.5)); }
            50% { transform: scale(1.15); filter: drop-shadow(0 0 20px rgba(253,230,138,0.95)); }
          }
          @keyframes starTwinkle {
            0%, 100% { opacity: 0.2; transform: scale(0.7) rotate(0deg); }
            50% { opacity: 1; transform: scale(1.3) rotate(45deg); filter: drop-shadow(0 0 8px #FDE68A); }
          }
          @keyframes auraBreathe {
            0%, 100% { transform: scale(1) translate(0px, 0px); opacity: 0.25; }
            50% { transform: scale(1.2) translate(15px, -20px); opacity: 0.45; }
          }
          .anim-crown-glow { animation: pulseCrown 2.5s ease-in-out infinite; }
          .anim-aura-glow { animation: auraBreathe 8s ease-in-out infinite; }

          .page-sheet-item {
            background-color: #0A1428;
            box-shadow: inset 0 0 45px rgba(0, 0, 0, 0.85);
            overflow: hidden;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            box-sizing: border-box;
          }
        `}</style>

                {/* BACKGROUND KERAJAAN MEGAH */}
                <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden">
                    <svg className="absolute inset-0 w-full h-full opacity-[0.06] select-none" xmlns="http://www.w3.org/2000/svg">
                        <defs>
                            <pattern id="royalDamaskBigGrid" width="56" height="56" patternUnits="userSpaceOnUse">
                                <path
                                    d="M 28 0 C 35 12 44 21 56 28 C 44 35 35 44 28 56 C 21 44 12 35 0 28 C 12 21 21 12 28 0 Z"
                                    stroke="#F59E0B"
                                    strokeWidth="0.8"
                                    fill="none"
                                />
                                <circle cx="28" cy="28" r="4" fill="#FDE68A" opacity="0.8" />
                                <circle cx="0" cy="0" r="2.5" fill="#F59E0B" />
                                <circle cx="56" cy="0" r="2.5" fill="#F59E0B" />
                                <circle cx="0" cy="56" r="2.5" fill="#F59E0B" />
                                <circle cx="56" cy="56" r="2.5" fill="#F59E0B" />
                                <path d="M 14 14 L 42 42 M 42 14 L 14 42" stroke="#FDE68A" strokeWidth="0.4" strokeDasharray="1 3" />
                            </pattern>
                        </defs>
                        <rect width="100%" height="100%" fill="url(#royalDamaskBigGrid)" />
                    </svg>

                    <div className="absolute -top-16 left-1/2 -translate-x-1/2 w-[420px] h-[420px] bg-radial from-[#F59E0B]/30 via-[#BE123C]/15 to-transparent blur-3xl anim-aura-glow" />
                    <div className="absolute top-[42%] -right-24 w-[380px] h-[380px] bg-radial from-[#D97706]/25 via-transparent to-transparent blur-3xl anim-aura-glow" style={{ animationDelay: '-3s' }} />
                    <div className="absolute bottom-16 -left-20 w-[400px] h-[400px] bg-radial from-[#B45309]/25 via-transparent to-transparent blur-3xl anim-aura-glow" style={{ animationDelay: '-5s' }} />

                    <CelestialMandalaBackground />

                    {TWINKLING_STARS.map((star) => (
                        <div
                            key={star.id}
                            style={{
                                position: 'absolute',
                                top: star.top,
                                left: star.left,
                                right: star.right,
                                animation: `starTwinkle ${star.duration} ease-in-out infinite`,
                                animationDelay: star.delay,
                            }}
                        >
                            <DiamondStar size={star.size} />
                        </div>
                    ))}

                    {GOLDEN_STARDUST.map((dust) => (
                        <div
                            key={dust.id}
                            style={{
                                position: 'absolute',
                                left: dust.left,
                                width: `${dust.size}px`,
                                height: `${dust.size}px`,
                                borderRadius: '50%',
                                backgroundColor: '#FDE68A',
                                boxShadow: '0 0 10px #F59E0B, 0 0 18px #FDE68A',
                                animation: `stardustFloat ${dust.duration} ease-in infinite`,
                                animationDelay: dust.delay,
                                opacity: dust.opacity,
                            }}
                        />
                    ))}
                </div>

                {/* HEADER NAVBAR */}
                <header className="sticky top-0 z-40 bg-[#070D19]/90 backdrop-blur-xl border-b border-[#F59E0B]/35 px-5 py-3.5 flex items-center justify-between shadow-[0_4px_25px_rgba(0,0,0,0.5)]">
                    <Link
                        href="/acara"
                        className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full border border-[#F59E0B] bg-gradient-to-r from-[#92400E] to-[#B45309] text-white text-[10.5px] font-mono tracking-wider uppercase font-bold hover:brightness-110 active:scale-95 transition-all shadow-[0_2px_10px_rgba(217,119,6,0.3)]"
                    >
                        <span>← Konfirmasi Hadir</span>
                    </Link>
                    <div className="flex flex-col items-end">
                        <span className="text-[9.5px] font-mono tracking-[0.28em] text-[#FDE68A] uppercase font-extrabold drop-shadow-xs">
                            Kitab Doa Tamu
                        </span>
                        <span className="text-[8.5px] font-mono text-[#FDA4AF] tracking-widest uppercase font-semibold">
                            Silvia &amp; Riyandi
                        </span>
                    </div>
                </header>

                <div className="px-2.5 sm:px-4 pt-5 space-y-4 relative z-10">

                    <section className="text-center space-y-2.5 px-2">
                        <div className="inline-flex items-center justify-center">
                            <span className="text-3xl anim-crown-glow">👑</span>
                        </div>

                        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[#F59E0B] bg-gradient-to-r from-[#0B1528] via-[#162744] to-[#0B1528] backdrop-blur-md shadow-[0_4px_20px_rgba(245,158,11,0.3)]">
                            <span className="w-2 h-2 rounded-full bg-[#FDE68A] shadow-[0_0_10px_#FDE68A] animate-ping" />
                            <span className="text-[10px] font-mono tracking-[0.25em] text-[#FDE68A] uppercase font-extrabold">
                                {wishes.length} Doa Restu • {totalHadir} Tamu Hadir
                            </span>
                            <span className="w-2 h-2 rounded-full bg-[#FDE68A] shadow-[0_0_10px_#FDE68A] animate-ping" />
                        </div>

                        <h1 className="text-2xl font-serif text-white font-extrabold tracking-wide drop-shadow-[0_2px_12px_rgba(245,158,11,0.5)]">
                            Kisah Kasih &amp; Restu Sahabat
                        </h1>
                    </section>

                    <div className="relative rounded-[32px] bg-gradient-to-br from-[#0D182E] via-[#08101F] to-[#040812] border-2 border-[#F59E0B]/80 shadow-[0_22px_70px_rgba(0,0,0,0.9),3px_3px_0_#92400E,6px_6px_0_#451A03] p-2 sm:p-2.5 overflow-hidden">

                        {/* Tumpukan Kertas Emas Sisi Kanan & Bawah */}
                        <div className="absolute right-0.5 top-4 bottom-4 w-1.5 bg-gradient-to-b from-[#FDE68A] via-[#F59E0B] to-[#78350F] opacity-75 rounded-r pointer-events-none" />
                        <div className="absolute bottom-0.5 left-6 right-6 h-1.5 bg-gradient-to-r from-[#FDE68A] via-[#F59E0B] to-[#78350F] opacity-75 rounded-b pointer-events-none" />

                        {/* Punggung Buku Kiri */}
                        <div className="absolute top-0 bottom-0 left-0 w-3.5 bg-gradient-to-r from-[#03060C] via-[#0E1A30] to-transparent border-r border-[#F59E0B]/40 z-30 pointer-events-none flex flex-col justify-between py-6 items-center opacity-85">
                            <div className="w-1.5 h-1.5 rounded-full bg-[#FDE68A] shadow-[0_0_4px_#F59E0B]" />
                            <div className="w-1 h-3 border-l border-dashed border-[#F59E0B]/60" />
                            <div className="w-1.5 h-1.5 rounded-full bg-[#FDE68A] shadow-[0_0_4px_#F59E0B]" />
                            <div className="w-1 h-3 border-l border-dashed border-[#F59E0B]/60" />
                            <div className="w-1.5 h-1.5 rounded-full bg-[#FDE68A] shadow-[0_0_4px_#F59E0B]" />
                        </div>

                        {/* Pita Pembatas Buku Merah Maroon */}
                        <div className="absolute top-0 right-8 z-30 pointer-events-none flex flex-col items-center">
                            <div className="w-5 h-8 bg-gradient-to-b from-[#BE123C] to-[#9F1239] shadow-md border-x border-[#FDE68A]/60 flex items-center justify-center">
                                <span className="text-[9px] font-mono text-[#FDE68A] font-bold">📖</span>
                            </div>
                            <div className="w-0 h-0 border-l-[10px] border-l-transparent border-r-[10px] border-r-transparent border-t-[7px] border-t-[#9F1239]" />
                        </div>

                        {/* Bingkai Dalam Lembaran */}
                        <div className="relative rounded-[26px] bg-[#050B17] border border-[#F59E0B]/40 min-h-[580px] flex flex-col justify-between p-3 sm:p-4 pl-4.5 sm:pl-5 overflow-hidden">

                            {/* Header Lembaran */}
                            <div className="flex items-center justify-between pb-2.5 border-b border-[#F59E0B]/30 relative z-20">
                                <div className="flex items-center gap-2">
                                    <span className="w-2 h-2 rotate-45 bg-[#FDE68A] shadow-[0_0_6px_#F59E0B]" />
                                    <span className="text-[10px] font-mono tracking-[0.2em] text-[#FDE68A] uppercase font-extrabold">
                                        Lembaran {currentPage + 1} Dari {totalSheets}
                                    </span>
                                </div>
                                <span className="text-[9px] font-mono text-[#CBD5E1] tracking-wider pr-6">
                                    {filteredWishes.length} Doa Tercatat
                                </span>
                            </div>

                            {/* AREA PANGGUNG FISIKA BUKU */}
                            <div className="py-2 flex-1 relative z-10 min-h-[520px] flex items-center justify-center">
                                {!isLoaded ? (
                                    <div className="py-24 text-center space-y-2">
                                        <div className="w-10 h-10 mx-auto rounded-full border-2 border-[#FDE68A] border-t-transparent animate-spin" />
                                        <p className="text-xs font-mono text-[#FDE68A] tracking-widest uppercase pt-2">
                                            Membuka Lembaran...
                                        </p>
                                    </div>
                                ) : wishes.length === 0 ? (
                                    <div className="py-16 text-center space-y-3 rounded-2xl border-2 border-dashed border-[#F59E0B]/40 bg-[#060D1A]/60 p-6 my-auto">
                                        <div className="text-3xl">💌</div>
                                        <h3 className="text-sm font-serif font-bold text-white tracking-wide">
                                            Lembaran Masih Bersih
                                        </h3>
                                        <p className="text-xs text-[#94A3B8] max-w-xs mx-auto">
                                            Jadilah orang pertama yang menorehkan ucapan di kitab pernikahan ini!
                                        </p>
                                        <div className="pt-2">
                                            <Link
                                                href="/acara"
                                                className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full border border-[#FDE68A] bg-gradient-to-r from-[#92400E] to-[#D97706] text-white text-xs font-mono font-bold tracking-wider hover:brightness-110 active:scale-95 transition-all shadow-md"
                                            >
                                                <span>✍️ Tulis Doa Sekarang</span>
                                            </Link>
                                        </div>
                                    </div>
                                ) : (
                                    <div
                                        key={bookKey}
                                        ref={bookElRef}
                                        className="w-full h-[530px] mx-auto overflow-hidden relative select-none"
                                    >
                                        {sheets.map((sheetItems, sheetIdx) => (
                                            <div
                                                key={sheetIdx}
                                                className="page-sheet-item p-4 sm:p-5 pl-5 sm:pl-6 border-r border-[#FDE68A]/60"
                                                data-density="soft"
                                                style={{
                                                    backgroundImage: `
                            radial-gradient(rgba(245, 158, 11, 0.25) 0.75px, transparent 0.75px),
                            linear-gradient(to bottom, rgba(253, 230, 138, 0.05) 1px, transparent 1px)
                          `,
                                                    backgroundSize: '10px 10px, 100% 16px',
                                                }}
                                            >
                                                {/* Tekstur Bayangan Jilid Kiri */}
                                                <div className="absolute top-0 bottom-0 left-0 w-6 bg-gradient-to-r from-black/90 via-black/40 to-transparent pointer-events-none z-20" />

                                                {/* DAFTAR 2 KARTU BESAR PER LEMBAR */}
                                                <div className="flex-1 flex flex-col justify-around gap-3.5 relative z-10 py-1">
                                                    {sheetItems.map((item) => (
                                                        <div
                                                            key={item.id}
                                                            className="group relative rounded-[22px] bg-gradient-to-b from-[#111D36]/95 via-[#0B1528]/95 to-[#060D1A] border border-[#F59E0B]/50 p-4 shadow-[0_8px_25px_rgba(0,0,0,0.6)] hover:border-[#FDE68A] transition-all overflow-hidden"
                                                        >
                                                            <MiniCornerFiligree className="absolute -top-1 -left-1 opacity-60" />
                                                            <MiniCornerFiligree className="absolute -top-1 -right-1 scale-x-[-1] opacity-60" />
                                                            <MiniCornerFiligree className="absolute -bottom-1 -left-1 scale-y-[-1] opacity-60" />
                                                            <MiniCornerFiligree className="absolute -bottom-1 -right-1 rotate-180 opacity-60" />

                                                            {/* Garis Halo Atas Kartu */}
                                                            <div className="absolute top-0 left-10 right-10 h-[1.5px] bg-gradient-to-r from-transparent via-[#FDE68A]/80 to-transparent flex items-center justify-center">
                                                                <div className="w-1.5 h-1.5 rotate-45 bg-[#FDE68A] shadow-[0_0_6px_#F59E0B]" />
                                                            </div>

                                                            {/* Watermark Tanda Kutip */}
                                                            <span className="absolute -right-1 -bottom-4 text-7xl font-serif text-[#FDE68A]/5 select-none pointer-events-none group-hover:text-[#FDE68A]/10 transition-colors">
                                                                &rdquo;
                                                            </span>

                                                            {/* Header Kartu: Avatar + Info Tamu */}
                                                            <div className="flex items-center gap-3.5 relative z-10">
                                                                <div className="relative w-12 h-12 shrink-0 flex items-center justify-center">
                                                                    <RotatingAvatarWreath />
                                                                    <div className="w-9.5 h-9.5 rounded-full overflow-hidden p-[1.5px] bg-gradient-to-tr from-[#FDE68A] via-[#F59E0B] to-[#92400E] shadow-[0_0_10px_rgba(245,158,11,0.5)]">
                                                                        <img
                                                                            src={getAutoGeneratedPhoto(item.name)}
                                                                            alt={item.name}
                                                                            onError={(e) => {
                                                                                e.currentTarget.src = `https://ui-avatars.com/api/?name=${encodeURIComponent(
                                                                                    item.name
                                                                                )}&background=0B1528&color=FDE68A&bold=true`;
                                                                            }}
                                                                            className="w-full h-full object-cover rounded-full filter contrast-105"
                                                                        />
                                                                    </div>
                                                                    <span className="absolute bottom-0 right-0 w-3 h-3 rounded-full bg-emerald-500 border border-[#0B1528] shadow-[0_0_5px_#10B981]" />
                                                                </div>

                                                                <div className="flex-1 min-w-0">
                                                                    {/* Nama Pengirim Full & Bebas Terpotong */}
                                                                    <div className="flex flex-wrap items-center justify-between gap-x-2 gap-y-1">
                                                                        <h4 className="text-sm font-serif font-extrabold text-white tracking-wide break-words">
                                                                            {item.name}
                                                                        </h4>
                                                                        <span className="text-[8.5px] font-mono text-[#FDE68A] font-semibold shrink-0 bg-[#040812] px-2 py-0.5 rounded border border-[#F59E0B]/40">
                                                                            {item.createdAt}
                                                                        </span>
                                                                    </div>

                                                                    <div className="flex items-center gap-2 mt-1">
                                                                        {item.attendance && (
                                                                            <span
                                                                                className={`inline-flex items-center gap-1 text-[8px] font-mono px-2 py-0.5 rounded-full font-bold border ${item.attendance.includes('Hadir') && !item.attendance.includes('Berhalangan')
                                                                                    ? 'border-emerald-400/80 bg-gradient-to-r from-emerald-950/90 to-[#062419] text-emerald-300 shadow-[0_0_8px_rgba(16,185,129,0.25)]'
                                                                                    : 'border-rose-400/80 bg-gradient-to-r from-rose-950/90 to-[#280911] text-rose-300 shadow-[0_0_8px_rgba(244,63,94,0.25)]'
                                                                                    }`}
                                                                            >
                                                                                <span>{item.attendance.includes('Berhalangan') ? '🕊️' : '✓'}</span>
                                                                                <span>{item.attendance}</span>
                                                                            </span>
                                                                        )}
                                                                        <span className="text-[8px] font-mono text-[#CBD5E1] px-2 py-0.5 rounded-full bg-[#162744]/80 border border-[#F59E0B]/30">
                                                                            {item.relationship || 'Tamu Undangan'}
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            {/* Isi Pesan Doa */}
                                                            <div className="mt-3 pt-2 border-t border-[#F59E0B]/20 relative z-10">
                                                                <p className="text-xs sm:text-[12.5px] text-[#F1F5F9] font-sans leading-relaxed text-justify italic pl-2 border-l-2 border-[#F59E0B]/80">
                                                                    &ldquo;{item.message}&rdquo;
                                                                </p>
                                                            </div>

                                                            {/* Stempel Segel */}
                                                            <div className="pt-2 flex justify-end items-center relative z-10">
                                                                <div className="inline-flex items-center gap-1 px-2 py-0.5 rounded border border-[#F59E0B]/40 bg-[#0A1426] shadow-xs">
                                                                    <span className="w-1.5 h-1.5 rounded-full bg-[#FDE68A]" />
                                                                    <span className="text-[7.5px] font-serif tracking-widest text-[#FDE68A] uppercase font-bold">
                                                                        Verified Guest • S &amp; R
                                                                    </span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    ))}
                                                </div>

                                                {/* Footer Lembaran */}
                                                <div className="pt-2 flex items-center justify-between border-t border-[#F59E0B]/25 text-[8.5px] font-mono text-[#CBD5E1]">
                                                    <span className="tracking-widest uppercase text-[#FDE68A] font-bold">
                                                        Halaman {sheetIdx + 1}
                                                    </span>
                                                    <span className="italic text-[#94A3B8]">
                                                        Kitab Doa Pernikahan Silvia &amp; Riyandi
                                                    </span>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>

                            {/* FOOTER NAVIGASI TOMBOL & FOLIO DOTS */}
                            <div className="pt-2.5 border-t border-[#F59E0B]/30 relative z-20 flex items-center justify-between">
                                <button
                                    type="button"
                                    title="Balik ke Lembar Sebelumnya"
                                    disabled={currentPage === 0}
                                    onClick={handleTurnPrev}
                                    className="w-9 h-9 rounded-full border border-[#F59E0B]/70 bg-gradient-to-r from-[#0E1A30] to-[#162744] text-[#FDE68A] text-lg flex items-center justify-center hover:border-[#FDE68A] hover:brightness-125 active:scale-90 disabled:opacity-20 disabled:pointer-events-none transition-all shadow-sm cursor-pointer"
                                >
                                    <span className="-ml-0.5">‹</span>
                                </button>

                                <div className="flex flex-col items-center gap-0.5">
                                    <span className="text-[9.5px] font-mono tracking-[0.2em] text-[#FDE68A] font-extrabold uppercase">
                                        Halaman {currentPage + 1} / {totalSheets}
                                    </span>
                                    <div className="flex items-center gap-1">
                                        {Array.from({ length: totalSheets }).map((_, idx) => (
                                            <span
                                                key={idx}
                                                className={`h-1.5 rounded-full transition-all duration-300 ${idx === currentPage
                                                    ? 'w-4 bg-[#FDE68A] shadow-[0_0_6px_#F59E0B]'
                                                    : 'w-1.5 bg-[#F59E0B]/30'
                                                    }`}
                                            />
                                        ))}
                                    </div>
                                    <span className="text-[8px] font-mono text-[#FDE68A]/70 pt-0.5">
                                        Sentuh &amp; tarik sudut untuk membalik lembaran
                                    </span>
                                </div>

                                <button
                                    type="button"
                                    title="Buka Lembar Berikutnya"
                                    disabled={currentPage >= totalSheets - 1}
                                    onClick={handleTurnNext}
                                    className="w-9 h-9 rounded-full border border-[#FDE68A] bg-gradient-to-r from-[#92400E] via-[#D97706] to-[#92400E] text-white text-lg flex items-center justify-center hover:brightness-125 active:scale-90 disabled:opacity-20 disabled:pointer-events-none transition-all shadow-[0_2px_10px_rgba(217,119,6,0.4)] cursor-pointer"
                                >
                                    <span className="-mr-0.5">›</span>
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* FOOTER NAVIGASI KEMBALI */}
                    <footer className="pt-3 flex flex-col items-center gap-3">
                        <Link
                            href="/acara"
                            className="w-full py-3.5 px-4 rounded-xl border-2 border-[#FDE68A] bg-gradient-to-r from-[#92400E] via-[#D97706] to-[#92400E] text-white text-xs font-mono font-bold tracking-wider hover:brightness-110 active:scale-98 transition-all flex items-center justify-center gap-2 shadow-[0_6px_25px_rgba(217,119,6,0.4)]"
                        >
                            <span>✍️ Tulis Doa &amp; Konfirmasi Hadir</span>
                            <span className="text-sm text-[#FDE68A]">→</span>
                        </Link>

                        <Link
                            href="/?opened=true"
                            className="text-[11px] font-mono text-[#94A3B8] hover:text-[#FDE68A] underline tracking-wider pt-1 transition-colors"
                        >
                            Kembali ke Halaman Utama Undangan
                        </Link>
                    </footer>
                </div>
            </main>
        </div>
    );
}